/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rrhh.vista;

import rrhh.modelo.daoAsignacion;
import rrhh.controlador.clsAsignacion;

import rrhh.modelo.daoGeneracion;
import rrhh.controlador.clsGeneracion;

import java.util.List;

import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListModel;
import java.io.File;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author visitante
 */
public class frmVisualizacion extends javax.swing.JInternalFrame {

    
    
    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id");
        modelo.addColumn("fecha inicial");
        modelo.addColumn("fecha final");
        modelo.addColumn("nombre");
        modelo.addColumn("concepto");
        modelo.addColumn("valor");
     
        daoGeneracion generaDAO = new daoGeneracion();
        List<clsGeneracion> envia = generaDAO.select();
        tablanomina.setModel(modelo);
        String[] dato = new String[8];
        for (int i = 0; i < envia.size(); i++) {
            dato[0] = Integer.toString(envia.get(i).getgeid());
            dato[1] = envia.get(i).getgeinicial();
            dato[2] = envia.get(i).getgefinal();
            dato[3] = envia.get(i).getgenombre();
            dato[4] = envia.get(i).getgeconcepto();
            dato[5] = envia.get(i).getgevalor();
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

   
    public void autollenado(){
    
    int contador=1;
    consultar = JOptionPane.showInputDialog("Generacion de nominas" + "Numero de empleados" + c+".");
    int a = Integer.parseInt(consultar);
     clsAsignacion asignacionAConsultar = new clsAsignacion();
        daoAsignacion asignacionDAO = new daoAsignacion();
        
     daoGeneracion nominaDAO = new daoGeneracion();
        clsGeneracion nominaAInsertar = new clsGeneracion();   
        
    while(contador <= a){
    
    asignacionAConsultar.setaid(contador);
    asignacionAConsultar = asignacionDAO.query(asignacionAConsultar); 
     
     asignacionAConsultar.getanombre();
     asignacionAConsultar.getaconcepto();
     asignacionAConsultar.getavalor();
    
     nominaAInsertar.setgeinicial(Finicial.getText());
     nominaAInsertar.setgefinal(Ffinal.getText());
     nominaAInsertar.setgenombre(asignacionAConsultar.getanombre());
     nominaAInsertar.setgeconcepto(asignacionAConsultar.getaconcepto());
     nominaAInsertar.setgevalor(asignacionAConsultar.getavalor());  
     nominaDAO.insert(nominaAInsertar);
      llenadoDeTablas();
      
      contador++;
   
    }
    
    }   
    
     public void autoEliminado(){
    
    int contador=1;
     daoGeneracion autollenadoDAO = new daoGeneracion();
     clsGeneracion autollenadoAEliminar = new clsGeneracion();;
        
    while(contador <= 200){
    
      autollenadoAEliminar.setgeid(contador);
      autollenadoDAO.delete(autollenadoAEliminar);
      llenadoDeTablas();
      contador++;
   
    }
    
    }   
    
    public frmVisualizacion() {
        initComponents();
        llenadoDeTablas();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btnGenerar = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablanomina = new javax.swing.JTable();
        label5 = new javax.swing.JLabel();
        Finicial = new javax.swing.JTextField();
        label9 = new javax.swing.JLabel();
        Ffinal = new javax.swing.JTextField();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        jCheckBox1.setText("jCheckBox1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Generar");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerar.setText("Generar registros");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 120, -1));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText(".");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 20, 20));

        tablanomina.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablanomina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "fecha inicial", "fecha final", "nombre", "conceptos", "valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablanomina);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 570, 303));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label5.setText("----------Visualizacion-----------");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));
        getContentPane().add(Finicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 220, 30));

        label9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label9.setText("Fecha final");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 70, 20));
        getContentPane().add(Ffinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 220, 30));

        label6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label6.setText("Fecha inicial");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        label7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label7.setText("----------Generacion de nominas-----------");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        btnEliminar.setText("Eliminar registros");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 int c = 0;
 String consultar="";
    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
     
        autollenado();
        
      
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        autoEliminado();
    }//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ffinal;
    private javax.swing.JTextField Finicial;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablanomina;
    // End of variables declaration//GEN-END:variables
}
