/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.vista;

import seguridad.modelo.daoUsuario;
import seguridad.controlador.clsUsuario;
import seguridad.modelo.daoPerfil;
import seguridad.controlador.clsPerfil;
import seguridad.modelo.daoPerfilUsuario;
import seguridad.controlador.clsPerfilUsuario;
import java.util.List;

import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListModel;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author visitante
 */
public class frmMantenimientoPperfilusuarios extends javax.swing.JInternalFrame {

    public void llenadoDeCombos() {
        daoUsuario usuarioDAO = new daoUsuario();
        List<clsUsuario> usuarios = usuarioDAO.select();
        cbox_usuarios.addItem("Seleccione una opción");
        for (int i = 0; i < usuarios.size(); i++) {
            cbox_usuarios.addItem(usuarios.get(i).getUsunombre());
        }
    }
    
    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id");
        modelo.addColumn("Perfil");
        modelo.addColumn("Nombre");
        daoPerfilUsuario perfilusuarioDAO = new daoPerfilUsuario();
        List<clsPerfilUsuario> perfilusuarios = perfilusuarioDAO.select();
        tablaasignacion.setModel(modelo);
        String[] dato = new String[8];
        for (int i = 0; i < perfilusuarios.size(); i++) {
            dato[0] = Integer.toString(perfilusuarios.get(i).getId_PerfilUsuario());
            dato[1] = perfilusuarios.get(i).getNombrePerfil();
            dato[2] = perfilusuarios.get(i).getNombreUsuario();
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    
    
  

    public void buscarperfil() {
        clsPerfil perfilAConsultar = new clsPerfil();
        daoPerfil perfilDAO = new daoPerfil();
        perfilAConsultar.setId_Perfil(Integer.parseInt(txtbuscado.getText()));
        perfilAConsultar = perfilDAO.query(perfilAConsultar);
        txtNombre.setText(perfilAConsultar.getNombrePerfil());        
    }

    public frmMantenimientoPperfilusuarios() {
        initComponents();
        llenadoDeTablas();
        llenadoDeCombos();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        lb = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaasignacion = new javax.swing.JTable();
        label4 = new javax.swing.JLabel();
        cbox_usuarios = new javax.swing.JComboBox<>();
        label2 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento Perfil Usuarios");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 95, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 95, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 95, -1));

        label1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label1.setText("Buscar perfil");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText(".");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 20, -1));
        getContentPane().add(txtbuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 102, -1));

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtNombre.setOpaque(false);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 185, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 95, -1));

        lb.setForeground(new java.awt.Color(204, 204, 204));
        lb.setText(".");
        getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 22, 13, -1));

        tablaasignacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaasignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Perfil", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaasignacion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 300, 303));

        label4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label4.setText("Nombre");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 20, -1, -1));

        cbox_usuarios.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbox_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_usuariosActionPerformed(evt);
            }
        });
        getContentPane().add(cbox_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 220, -1));

        label2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label2.setText("Usuarios asignados");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label5.setText("Usuarios disponibles");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int c = 0;
        String consultar="";
        consultar = JOptionPane.showInputDialog("Eliminar Asignacion" + " Ingresar numero de ID que aparece en la tabla derecha." + c+".");
        
        
        
        daoPerfilUsuario perfilusuarioDAO = new daoPerfilUsuario();
        clsPerfilUsuario perfilusuarioAEliminar = new clsPerfilUsuario();;
        perfilusuarioAEliminar.setId_PerfilUsuario(Integer.parseInt(consultar));
        perfilusuarioDAO.delete(perfilusuarioAEliminar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        daoPerfilUsuario perfilusuarioDAO = new daoPerfilUsuario();
        clsPerfilUsuario perfilusuarioAInsertar = new clsPerfilUsuario();
        perfilusuarioAInsertar.setNombrePerfil(txtNombre.getText());
        perfilusuarioAInsertar.setNombreUsuario(cbox_usuarios.getSelectedItem().toString());
        perfilusuarioDAO.insert(perfilusuarioAInsertar);
        llenadoDeTablas();
        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarperfil();
 
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
        txtNombre.setText("");
        
        txtbuscado.setText("");
        btnRegistrar.setEnabled(true);
        btnEliminar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbox_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_usuariosActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_usuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbox_usuarios;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaasignacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
