/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas.reportes;


import ventas.vista.*;
import ventas.modelo.daoVentas;
import ventas.controlador.clsVentas;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import ventas.controlador.archivo_correo;
import ventas.controlador.clsClientes;
import ventas.controlador.clsCotizaciones;
import ventas.controlador.clsProductos;
import ventas.controlador.clsVendedores;
import ventas.controlador.mail_api;
import ventas.modelo.daoClientes;
import ventas.modelo.daoCotizaciones;
import ventas.modelo.daoProductos;
import ventas.modelo.daoVendedores;
import ventas.modelo.daoVentas;


/**
 *
 * @author visitante
 */




public class frmVentas extends javax.swing.JInternalFrame {
     DefaultTableModel modelo;
     Object[] info = new Object[4];
    Api_pdf creacion = new Api_pdf();
   

public int verificar_existencias(int existencias, int cantidad){
      int nueva=existencias-cantidad;
return nueva;
}


public void actualizar_existencias(String producto, int existencias, int cantidad_compra){
       int nueva=existencias-cantidad_compra;
        daoProductos productoDAO = new daoProductos();
        clsProductos productoAActualizar = new clsProductos();
        productoDAO.update_total_value(producto,nueva);
}









    public void llenadoDeTablas() {
                modelo =(DefaultTableModel) tabladatos.getModel();
        daoProductos productosDAO = new daoProductos();
        List<clsProductos> productos = productosDAO.select();
        txtproducto.addItem("Seleccione una opción");
        for (int i = 0; i < productos.size(); i++) {
            txtproducto.addItem(productos.get(i).fGetproducto_Producto());
        }

        txtexistencia.addItem("Productos");
        for (int i = 0; i < productos.size(); i++) {
            txtexistencia.addItem(productos.get(i).fGetproducto_Producto()+" Existencia: "+productos.get(i).fGetexistencia_Producto());
        }
    
    }



    public frmVentas() {
        initComponents();
        llenadoDeTablas();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        label5 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        label7 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JSpinner();
        txtidcliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtproducto = new javax.swing.JComboBox<>();
        txtexistencia = new javax.swing.JComboBox<>();
        label8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        tipopago = new javax.swing.JComboBox<>();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ventas");
        setVisible(true);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label5.setText("Cantidad");

        lb.setForeground(new java.awt.Color(204, 204, 204));
        lb.setText(".");

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label7.setText("Producto");

        label9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label9.setText("ID Cliente");

        txtcantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabladatos);

        jButton1.setText("borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Confirmar Orden de Venta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductoActionPerformed(evt);
            }
        });

        txtexistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexistenciaActionPerformed(evt);
            }
        });

        label8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label8.setText("Existencias");

        jButton4.setText("Cotizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tipopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Pago", "Efectivo", "Tarjeta", "Cheque", "Credito" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(213, 698, Short.MAX_VALUE)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(167, 167, 167)
                                        .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(111, 111, 111))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(label9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)))
                                .addComponent(label7)
                                .addGap(18, 18, 18)
                                .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(label5)
                                .addGap(6, 6, 6)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label8)
                                .addGap(18, 18, 18)
                                .addComponent(txtexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(290, 290, 290)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(240, 240, 240))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tipopago, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label8)
                        .addComponent(txtexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRegistrar))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label5)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label7)
                        .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb)
                        .addComponent(label9)
                        .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(tipopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnLimpiar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        int cantidad_existencias=0;
        clsProductos productoAConsultar = new clsProductos();
        daoProductos productoDAO = new daoProductos();
        productoAConsultar.fSetproducto_Producto(String.valueOf(txtproducto.getSelectedItem()));
        productoAConsultar = productoDAO.query(productoAConsultar);
        cantidad_existencias=verificar_existencias(productoAConsultar.fGetexistencia_Producto(),Integer.parseInt(String.valueOf(txtcantidad.getValue())));
        if(cantidad_existencias<0){
           JOptionPane.showMessageDialog(null, "la cantidad no puede ser mayor a la existencia");
           }else{
       daoVentas ventasDAO = new daoVentas();
        productoAConsultar.fSetproducto_Producto(String.valueOf(txtproducto.getSelectedItem()));
        productoAConsultar = productoDAO.query(productoAConsultar);
        String tipo_cliente=ventasDAO.type(txtidcliente.getText());
        double precio=0;
        if(tipo_cliente.equals("mayorista")){
           precio=productoAConsultar.fGetpreciomayorista_Producto();
            }else if(tipo_cliente.equals("minorista")){
            precio=productoAConsultar.fGetpreciominorista_Producto();
            }
        info[0]=String.valueOf(txtproducto.getSelectedItem());
        info[1]=String.valueOf(txtcantidad.getValue());
        info[2]=String.valueOf(precio);    
        info[3]=String.valueOf(precio*Integer.parseInt(String.valueOf(txtcantidad.getValue())));  
        modelo.addRow(info);
}
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

      
        txtcantidad.setValue(0);
        txtproducto.setSelectedItem(0);
        txtidcliente.setText("");
        txtidcliente.setText("");
        btnRegistrar.setEnabled(true);
for (int i = 0; i < tabladatos.getRowCount(); i++) {
modelo.removeRow(i);
i-=1;
}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("src\\main\\java\\ayudas\\ProcesoMayor.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ayudas\\ProcesoMayor.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no Fue encontrada");
            }
            System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    int fila=tabladatos.getSelectedColumn();
    if(fila>=0){
        modelo.removeRow(fila);
        }else{
        JOptionPane.showMessageDialog(null, "Seleccione una fila porfavor");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         mail_api mail = new mail_api();
        int resp = JOptionPane.showConfirmDialog(null, "Al presionar Aceptar usted estÃ¡ seguro de procesar la compra\n"+"Â¿Esta seguro?",//<- EL MENSAJE
            "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
      
    if(resp == JOptionPane.NO_OPTION){
       
    }else if(resp == JOptionPane.YES_OPTION){
   double total=0;
    String pago=String.valueOf(tipopago.getSelectedItem());
    String datos[][]=new String[tabladatos.getRowCount()][3];
     java.util.Date fecha = new java.util.Date();
        LocalDate todaysDate = LocalDate.now(); 
        daoVentas ventasDAO = new daoVentas();
        clsVentas ventasAInsertar = new clsVentas();
        for (int i = 0; i < tabladatos.getRowCount(); i++) {
        
        ventasAInsertar.fSettipo_Venta(ventasDAO.type(txtidcliente.getText()));
        ventasAInsertar.fSetcantidad_Venta(Integer.parseInt(String.valueOf(tabladatos.getValueAt(i, 1))));
        ventasAInsertar.fSetproducto_Venta(String.valueOf(tabladatos.getValueAt(i, 0)));
        ventasAInsertar.fSetprecio_Venta(Double.parseDouble(String.valueOf(tabladatos.getValueAt(i, 2))));
        ventasAInsertar.fSettotal_Venta(Double.parseDouble(String.valueOf(tabladatos.getValueAt(i, 3))));
        ventasAInsertar.fSetfecha_Venta(String.valueOf(todaysDate));
        ventasAInsertar.fSetid_Cliente(Integer.parseInt(txtidcliente.getText()));
        ventasAInsertar.fSetid_Vendedor(ventasDAO.vendor(txtidcliente.getText()));
        ventasAInsertar.fSetpago_Cliente(pago);
        ventasDAO.insert(ventasAInsertar);
        total+=Double.parseDouble(String.valueOf(tabladatos.getValueAt(i, 3)));
        for(int j=0; j<3;j++){
        if(j==0){
                datos[i][j]=String.valueOf(tabladatos.getValueAt(i, 1));
        }else if(j==1){
                datos[i][j]=String.valueOf(tabladatos.getValueAt(i, 0));
        }else if(j==2){
                datos[i][j]=String.valueOf(tabladatos.getValueAt(i, 2));
        }
        }
        clsProductos productoAConsultar = new clsProductos();
        daoProductos productoDAO = new daoProductos();
        productoAConsultar.fSetproducto_Producto(String.valueOf(tabladatos.getValueAt(i, 0)));
        productoAConsultar = productoDAO.query(productoAConsultar);
        actualizar_existencias(String.valueOf(tabladatos.getValueAt(i, 0)),productoAConsultar.fGetexistencia_Producto(),Integer.parseInt(String.valueOf(tabladatos.getValueAt(i, 1))));
        
    }
JOptionPane.showMessageDialog(null, "La orden se Ha procesado con exito");
     mail.SendMailAPI(ventasDAO.email(String.valueOf(txtidcliente.getText())), "mensaje", "este es un mensaje de prueba","Orden de Compra", ventasDAO.name(String.valueOf(txtidcliente.getText())));
      creacion.creacion(datos, String.valueOf(todaysDate),ventasDAO.email(String.valueOf(txtidcliente.getText())),ventasDAO.name(String.valueOf(txtidcliente.getText())), "factura");
       daoClientes clientesDAO = new daoClientes();
        clsClientes clientesAInsertar = new clsClientes();  
    
        clsClientes clienteAConsultar = new clsClientes();
        daoClientes clienteDAO = new daoClientes();
        clienteAConsultar.fSetid_Clientes(Integer.parseInt(txtidcliente.getText()));
        clienteAConsultar = clienteDAO.query(clienteAConsultar);
        if(pago.equals("Credito")){
        clientesDAO.update_total_credit(Integer.parseInt(txtidcliente.getText()),total,clienteAConsultar.fGetcredito_Clientes());
        } 
        clsVendedores vendedorAConsultar = new clsVendedores();
        daoVendedores vendedorDAO = new daoVendedores();
        vendedorAConsultar.fSetid_Vendedores(ventasDAO.vendor(txtidcliente.getText()));
        vendedorAConsultar = vendedorDAO.query(vendedorAConsultar);
        vendedorDAO.update_total_sells(ventasDAO.vendor(txtidcliente.getText()),vendedorAConsultar.fGetventas_Vendedores()+1);
        
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductoActionPerformed

    private void txtexistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexistenciaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         mail_api mail = new mail_api();
        int resp = JOptionPane.showConfirmDialog(null, "Al presionar Aceptar usted está¡ seguro de procesar la cotizacion\n"+"¿Esta seguro?",//<- EL MENSAJE
            "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
      
    if(resp == JOptionPane.NO_OPTION){
       
    }else if(resp == JOptionPane.YES_OPTION){
    String datos[][]=new String[tabladatos.getRowCount()][3];
     java.util.Date fecha = new java.util.Date();
        LocalDate todaysDate = LocalDate.now(); 
        daoCotizaciones cotizacionesDAO = new daoCotizaciones();
        clsCotizaciones cotizacionAInsertar = new clsCotizaciones();
        daoVentas ventasDAO = new daoVentas();
        clsVentas ventasAInsertar = new clsVentas();
        for (int i = 0; i < tabladatos.getRowCount(); i++) {
        
        cotizacionAInsertar.fSetTipo_Cotizacion(ventasDAO.type(txtidcliente.getText()));
        cotizacionAInsertar.fSetCantidad_Cotizacion(Integer.parseInt(String.valueOf(tabladatos.getValueAt(i, 1))));
        cotizacionAInsertar.fSetProducto_Cotizacion(String.valueOf(tabladatos.getValueAt(i, 0)));
        cotizacionAInsertar.fSetPrecio_Cotizacion(Double.parseDouble(String.valueOf(tabladatos.getValueAt(i, 2))));
        cotizacionAInsertar.fSetTotal_Cotizacion(Double.parseDouble(String.valueOf(tabladatos.getValueAt(i, 3))));
        cotizacionAInsertar.fSetFecha_Cotizacion(String.valueOf(todaysDate));
        cotizacionAInsertar.fSetId_Cliente(Integer.parseInt(txtidcliente.getText()));
        cotizacionAInsertar.fSetid_Vendedor(ventasDAO.vendor(txtidcliente.getText()));
        cotizacionesDAO.insert(cotizacionAInsertar);
        for(int j=0; j<3;j++){
        if(j==0){
                datos[i][j]=String.valueOf(tabladatos.getValueAt(i, 1));
        }else if(j==1){
                datos[i][j]=String.valueOf(tabladatos.getValueAt(i, 0));
        }else if(j==2){
                datos[i][j]=String.valueOf(tabladatos.getValueAt(i, 2));
        }
        }
        
    }
JOptionPane.showMessageDialog(null, "La orden se Ha procesado con exito");
     mail.SendMailAPI(ventasDAO.email(String.valueOf(txtidcliente.getText())), "mensaje", "este es un mensaje de prueba","Cotizacion", ventasDAO.name(String.valueOf(txtidcliente.getText())));
      creacion.creacion(datos, String.valueOf(todaysDate),ventasDAO.email(String.valueOf(txtidcliente.getText())),ventasDAO.name(String.valueOf(txtidcliente.getText())),"cotizacion");
 }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tabladatos;
    private javax.swing.JComboBox<String> tipopago;
    private javax.swing.JSpinner txtcantidad;
    private javax.swing.JComboBox<String> txtexistencia;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JComboBox<String> txtproducto;
    // End of variables declaration//GEN-END:variables
}
