/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas.vista;


import ventas.vista.*;
import ventas.modelo.daoVentas;
import ventas.controlador.clsVentas;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import ventas.modelo.daoEncabezado_Ventas;
import ventas.controlador.archivo_correo;
import ventas.controlador.clsClientes;
import ventas.controlador.clsCotizaciones;
import ventas.controlador.clsDetalles_Cotizaciones;
import ventas.controlador.clsDetalles_Ventas;
import ventas.controlador.clsEncabezado_Cotizaciones;
import ventas.controlador.clsEncabezado_Ventas;
import ventas.controlador.clsProductos;
import ventas.controlador.clsVendedores;
import ventas.controlador.mail_api;
import ventas.modelo.daoClientes;
import ventas.modelo.daoCotizaciones;
import ventas.modelo.daoDetalles_Cotizaciones;
import ventas.modelo.daoDetalles_Ventas;
import ventas.modelo.daoEncabezado_Cotizaciones;
import ventas.modelo.daoProductos;
import ventas.modelo.daoVendedores;
import ventas.modelo.daoVentas;
import ventas.reportes.Api_pdf;


/**
 *
 * @author visitante
 */




public class frmVentas extends javax.swing.JInternalFrame {
     DefaultTableModel modelo;
     Object[] info = new Object[4];
    Api_pdf creacion = new Api_pdf();
   

public int verificar_existencias(int existencias, int cantidad){
      int nueva=existencias-cantidad;
return nueva;
}


public void actualizar_existencias(String producto, int existencias, int cantidad_compra){
       int nueva=existencias-cantidad_compra;
        daoProductos productoDAO = new daoProductos();
        clsProductos productoAActualizar = new clsProductos();
        productoDAO.update_total_value(producto,nueva);
}









    public void llenadoDeTablas() {
                modelo =(DefaultTableModel) tabladatos.getModel();
        daoProductos productosDAO = new daoProductos();
        List<clsProductos> productos = productosDAO.select();
        txtproducto.addItem("Seleccione una opción");
        for (int i = 0; i < productos.size(); i++) {
            txtproducto.addItem(productos.get(i).fGetproducto_Producto());
        }

        txtexistencia.addItem("Productos");
        for (int i = 0; i < productos.size(); i++) {
            txtexistencia.addItem(productos.get(i).fGetproducto_Producto()+" Existencia: "+productos.get(i).fGetexistencia_Producto());
        }
    
    }

 
    public frmVentas() {
        initComponents();
        llenadoDeTablas();


    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        label5 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        label7 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JSpinner();
        txtidcliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtproducto = new javax.swing.JComboBox<>();
        txtexistencia = new javax.swing.JComboBox<>();
        label8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        tipopago = new javax.swing.JComboBox<>();
        txttipocliente = new javax.swing.JLabel();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ventas");
        setVisible(true);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label5.setText("Cantidad");

        lb.setForeground(new java.awt.Color(204, 204, 204));
        lb.setText(".");

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label7.setText("Producto");

        label9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label9.setText("ID Cliente");

        txtcantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        txtidcliente.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtidclienteInputMethodTextChanged(evt);
            }
        });
        txtidcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidclienteActionPerformed(evt);
            }
        });
        txtidcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidclienteKeyReleased(evt);
            }
        });

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabladatos);

        jButton1.setText("borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Confirmar Orden de Venta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductoActionPerformed(evt);
            }
        });

        txtexistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexistenciaActionPerformed(evt);
            }
        });

        label8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label8.setText("Existencias");

        jButton4.setText("Cotizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tipopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Pago", "Efectivo", "Tarjeta", "Cheque", "Credito" }));

        txttipocliente.setBackground(new java.awt.Color(255, 255, 255));
        txttipocliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txttipocliente.setForeground(new java.awt.Color(0, 0, 255));
        txttipocliente.setText("Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(label9)
                                .addGap(18, 18, 18)
                                .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addComponent(label7)
                        .addGap(18, 18, 18)
                        .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(label5)
                        .addGap(6, 6, 6)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tipopago, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(668, 668, 668)))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(label8)
                .addGap(18, 18, 18)
                .addComponent(txtexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txttipocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label8)
                            .addComponent(txtexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txttipocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label5)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label7)
                                .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb)
                                .addComponent(label9)
                                .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnRegistrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(tipopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnLimpiar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
/*INICIO DE PRUEBA DEL DETALLE DE VENTAS Y ENCABEZADO
        daoEncabezado_Ventas EncabezadoVentasDAO = new daoEncabezado_Ventas();
        clsEncabezado_Ventas EncabezadoVentasAInsertar = new clsEncabezado_Ventas();
        EncabezadoVentasAInsertar.setFecha("11-11-2021");
        EncabezadoVentasAInsertar.setPago("efectivo");
        EncabezadoVentasAInsertar.setId_vendedor(2);
        EncabezadoVentasAInsertar.setId_cliente(5);
        EncabezadoVentasAInsertar.setTotal(110);
        EncabezadoVentasDAO.insert(EncabezadoVentasAInsertar);

        List<clsEncabezado_Ventas> encabezadoventas = EncabezadoVentasDAO.select();
        daoDetalles_Ventas DetallesVentasDAO = new daoDetalles_Ventas();
        clsDetalles_Ventas DetallesVentasAInsertar = new clsDetalles_Ventas();
        DetallesVentasAInsertar.setId_venta(encabezadoventas.get(0).getId_venta());
        DetallesVentasAInsertar.setProducto("camisas");
        DetallesVentasAInsertar.setCantidad(3);
        DetallesVentasAInsertar.setPrecio(50);
        DetallesVentasAInsertar.setTotal(150);
        DetallesVentasDAO.insert(DetallesVentasAInsertar);


/*FIN DE PRUEBA DEL DETALLE DE VENTAS Y ENCABEZADO*/


        int cantidad_existencias=0;
        clsProductos productoAConsultar = new clsProductos();
        daoProductos productoDAO = new daoProductos();
        productoAConsultar.fSetproducto_Producto(String.valueOf(txtproducto.getSelectedItem()));
        productoAConsultar = productoDAO.query(productoAConsultar);
        cantidad_existencias=verificar_existencias(productoAConsultar.fGetexistencia_Producto(),Integer.parseInt(String.valueOf(txtcantidad.getValue())));
        if(cantidad_existencias<0){
           JOptionPane.showMessageDialog(null, "la cantidad no puede ser mayor a la existencia");
           }else{
       daoVentas ventasDAO = new daoVentas();
        productoAConsultar.fSetproducto_Producto(String.valueOf(txtproducto.getSelectedItem()));
        productoAConsultar = productoDAO.query(productoAConsultar);
        String tipo_cliente=ventasDAO.type(txtidcliente.getText());
        double precio=0;
        if(tipo_cliente.equals("mayorista")){
           precio=productoAConsultar.fGetpreciomayorista_Producto();
            }else if(tipo_cliente.equals("minorista")){
            precio=productoAConsultar.fGetpreciominorista_Producto();
            }
        info[0]=String.valueOf(txtproducto.getSelectedItem());
        info[1]=String.valueOf(txtcantidad.getValue());
        info[2]=String.valueOf(precio);    
        info[3]=String.valueOf(precio*Integer.parseInt(String.valueOf(txtcantidad.getValue())));  
        modelo.addRow(info);
}
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

      
        txtcantidad.setValue(0);
        txtproducto.setSelectedItem(0);
        txtidcliente.setText("");
        txtidcliente.setText("");
        btnRegistrar.setEnabled(true);
for (int i = 0; i < tabladatos.getRowCount(); i++) {
modelo.removeRow(i);
i-=1;
}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("src\\main\\java\\ayudas\\ProcesoMayor.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ayudas\\ProcesoMayor.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no Fue encontrada");
            }
            System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    int fila=tabladatos.getSelectedColumn();
    if(fila>=0){
        modelo.removeRow(fila);
        }else{
        JOptionPane.showMessageDialog(null, "Seleccione una fila porfavor");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         mail_api mail = new mail_api();
        int resp = JOptionPane.showConfirmDialog(null, "Al presionar Aceptar usted estÃ¡ seguro de procesar la compra\n"+"Â¿Esta seguro?",//<- EL MENSAJE
            "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
      
    if(resp == JOptionPane.NO_OPTION){
       
    }else if(resp == JOptionPane.YES_OPTION){
    if(tipopago.getSelectedIndex()==0){
       JOptionPane.showMessageDialog(null, "Porfavor seleccione un metodo de pago");
      
}else{
   double total=0;
    String pago=String.valueOf(tipopago.getSelectedItem());
    String datos[][]=new String[tabladatos.getRowCount()][3];
     java.util.Date fecha = new java.util.Date();
        LocalDate todaysDate = LocalDate.now(); 
        daoEncabezado_Ventas ventasDAO = new daoEncabezado_Ventas();




/*probemos*/
        daoEncabezado_Ventas EncabezadoVentasDAO = new daoEncabezado_Ventas();
        clsEncabezado_Ventas EncabezadoVentasAInsertar = new clsEncabezado_Ventas();
        EncabezadoVentasAInsertar.setFecha(String.valueOf(todaysDate));
        EncabezadoVentasAInsertar.setPago(pago);
        EncabezadoVentasAInsertar.setId_vendedor(ventasDAO.vendor(txtidcliente.getText()));
        EncabezadoVentasAInsertar.setId_cliente(ventasDAO.vendor(txtidcliente.getText()));
        EncabezadoVentasAInsertar.setTipo_cliente(EncabezadoVentasDAO.type(String.valueOf(txtidcliente.getText())));

        for (int i = 0; i < tabladatos.getRowCount(); i++) {
total+=Double.parseDouble(String.valueOf(tabladatos.getValueAt(i, 3)));
}
        EncabezadoVentasAInsertar.setTotal(total);
        EncabezadoVentasDAO.insert(EncabezadoVentasAInsertar);

        for (int i = 0; i < tabladatos.getRowCount(); i++) {
        
/*probemos*/



        List<clsEncabezado_Ventas> encabezadoventas = EncabezadoVentasDAO.select();
        daoDetalles_Ventas DetallesVentasDAO = new daoDetalles_Ventas();
        clsDetalles_Ventas DetallesVentasAInsertar = new clsDetalles_Ventas();
        DetallesVentasAInsertar.setId_venta(encabezadoventas.get(encabezadoventas.size()-1).getId_venta());
        DetallesVentasAInsertar.setProducto(String.valueOf(tabladatos.getValueAt(i, 0)));
        DetallesVentasAInsertar.setCantidad(Integer.parseInt(String.valueOf(tabladatos.getValueAt(i, 1))));
        DetallesVentasAInsertar.setPrecio(Double.parseDouble(String.valueOf(tabladatos.getValueAt(i, 2))));
        DetallesVentasAInsertar.setTotal(Double.parseDouble(String.valueOf(tabladatos.getValueAt(i, 3))));
        DetallesVentasDAO.insert(DetallesVentasAInsertar);

/*fin probemos*/

      
        for(int j=0; j<3;j++){
        if(j==0){
                datos[i][j]=String.valueOf(tabladatos.getValueAt(i, 1));
        }else if(j==1){
                datos[i][j]=String.valueOf(tabladatos.getValueAt(i, 0));
        }else if(j==2){
                datos[i][j]=String.valueOf(tabladatos.getValueAt(i, 2));
        }
        }
        clsProductos productoAConsultar = new clsProductos();
        daoProductos productoDAO = new daoProductos();
        productoAConsultar.fSetproducto_Producto(String.valueOf(tabladatos.getValueAt(i, 0)));
        productoAConsultar = productoDAO.query(productoAConsultar);
        actualizar_existencias(String.valueOf(tabladatos.getValueAt(i, 0)),productoAConsultar.fGetexistencia_Producto(),Integer.parseInt(String.valueOf(tabladatos.getValueAt(i, 1))));
        
    }
JOptionPane.showMessageDialog(null, "La orden se Ha procesado con exito");
     mail.SendMailAPI(ventasDAO.email(String.valueOf(txtidcliente.getText())), "mensaje", "este es un mensaje de prueba","Orden de Compra", ventasDAO.name(String.valueOf(txtidcliente.getText())));
      creacion.creacion(datos, String.valueOf(todaysDate),ventasDAO.email(String.valueOf(txtidcliente.getText())),ventasDAO.name(String.valueOf(txtidcliente.getText())), "factura");
       daoClientes clientesDAO = new daoClientes();
        clsClientes clientesAInsertar = new clsClientes();  
    
        clsClientes clienteAConsultar = new clsClientes();
        daoClientes clienteDAO = new daoClientes();
        clienteAConsultar.fSetid_Clientes(Integer.parseInt(txtidcliente.getText()));
        clienteAConsultar = clienteDAO.query(clienteAConsultar);
        if(pago.equals("Credito")){
        clientesDAO.update_total_credit(Integer.parseInt(txtidcliente.getText()),total,clienteAConsultar.fGetcredito_Clientes());
        } 
        clsVendedores vendedorAConsultar = new clsVendedores();
        daoVendedores vendedorDAO = new daoVendedores();
        vendedorAConsultar.fSetid_Vendedores(ventasDAO.vendor(txtidcliente.getText()));
        vendedorAConsultar = vendedorDAO.query(vendedorAConsultar);
        vendedorDAO.update_total_sells(ventasDAO.vendor(txtidcliente.getText()),vendedorAConsultar.fGetventas_Vendedores()+1);
        
}}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductoActionPerformed

    private void txtexistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexistenciaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         mail_api mail = new mail_api();
        int resp = JOptionPane.showConfirmDialog(null, "Al presionar Aceptar usted está¡ seguro de procesar la cotizacion\n"+"¿Esta seguro?",//<- EL MENSAJE
            "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
      
    if(resp == JOptionPane.NO_OPTION){
       
    }else if(resp == JOptionPane.YES_OPTION){
    String datos[][]=new String[tabladatos.getRowCount()][3];
     java.util.Date fecha = new java.util.Date();
        LocalDate todaysDate = LocalDate.now(); 
        daoCotizaciones cotizacionesDAO = new daoCotizaciones();
        clsCotizaciones cotizacionAInsertar = new clsCotizaciones();
        daoVentas ventasDAO = new daoVentas();
        clsVentas ventasAInsertar = new clsVentas();


/*probemos*/
        daoEncabezado_Cotizaciones EncabezadoCotizacionesDAO = new daoEncabezado_Cotizaciones();
        clsEncabezado_Cotizaciones EncabezadoCotizacionesAInsertar = new clsEncabezado_Cotizaciones();
        EncabezadoCotizacionesAInsertar.setFecha(String.valueOf(todaysDate));
        EncabezadoCotizacionesAInsertar.setId_vendedor(ventasDAO.vendor(txtidcliente.getText()));
        EncabezadoCotizacionesAInsertar.setId_cliente(ventasDAO.vendor(txtidcliente.getText()));
        EncabezadoCotizacionesAInsertar.setTipo_cliente(EncabezadoCotizacionesDAO.type(String.valueOf(txtidcliente.getText())));
        double total2=0;
        for (int i = 0; i < tabladatos.getRowCount(); i++) {
total2+=Double.parseDouble(String.valueOf(tabladatos.getValueAt(i, 3)));
}
        EncabezadoCotizacionesAInsertar.setTotal(total2);
        EncabezadoCotizacionesDAO.insert(EncabezadoCotizacionesAInsertar);



        for (int i = 0; i < tabladatos.getRowCount(); i++) {
        
        /*probemos*/



        List<clsEncabezado_Cotizaciones> encabezadocotizaciones = EncabezadoCotizacionesDAO.select();
        daoDetalles_Cotizaciones DetallesCotizacionesDAO = new daoDetalles_Cotizaciones();
        clsDetalles_Cotizaciones DetallesCotizacionesAInsertar = new clsDetalles_Cotizaciones();
        DetallesCotizacionesAInsertar.setId_cotizacion(encabezadocotizaciones.get(encabezadocotizaciones.size()-1).getId_cotizacion());
        DetallesCotizacionesAInsertar.setProducto(String.valueOf(tabladatos.getValueAt(i, 0)));
        DetallesCotizacionesAInsertar.setCantidad(Integer.parseInt(String.valueOf(tabladatos.getValueAt(i, 1))));
        DetallesCotizacionesAInsertar.setPrecio(Double.parseDouble(String.valueOf(tabladatos.getValueAt(i, 2))));
        DetallesCotizacionesAInsertar.setTotal(Double.parseDouble(String.valueOf(tabladatos.getValueAt(i, 3))));
        DetallesCotizacionesDAO.insert(DetallesCotizacionesAInsertar);


 

/*fin probemos*/

        for(int j=0; j<3;j++){
        if(j==0){
                datos[i][j]=String.valueOf(tabladatos.getValueAt(i, 1));
        }else if(j==1){
                datos[i][j]=String.valueOf(tabladatos.getValueAt(i, 0));
        }else if(j==2){
                datos[i][j]=String.valueOf(tabladatos.getValueAt(i, 2));
        }
        }
        
    }
JOptionPane.showMessageDialog(null, "La orden se Ha procesado con exito");
     mail.SendMailAPI(ventasDAO.email(String.valueOf(txtidcliente.getText())), "mensaje", "este es un mensaje de prueba","Cotizacion", ventasDAO.name(String.valueOf(txtidcliente.getText())));
      creacion.creacion(datos, String.valueOf(todaysDate),ventasDAO.email(String.valueOf(txtidcliente.getText())),ventasDAO.name(String.valueOf(txtidcliente.getText())),"cotizacion");
 }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtidclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidclienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtidclienteActionPerformed

    private void txtidclienteInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtidclienteInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidclienteInputMethodTextChanged

    private void txtidclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidclienteKeyReleased
        // TODO add your handling code here:
        daoEncabezado_Ventas EncabezadoVentasDAO = new daoEncabezado_Ventas();
        clsEncabezado_Ventas EncabezadoVentasAInsertar = new clsEncabezado_Ventas();
        txttipocliente.setText("Nombre: "+EncabezadoVentasDAO.name(String.valueOf(txtidcliente.getText()))+" \nTipo: "+EncabezadoVentasDAO.type(String.valueOf(txtidcliente.getText())));
    }//GEN-LAST:event_txtidclienteKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tabladatos;
    private javax.swing.JComboBox<String> tipopago;
    private javax.swing.JSpinner txtcantidad;
    private javax.swing.JComboBox<String> txtexistencia;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JComboBox<String> txtproducto;
    private javax.swing.JLabel txttipocliente;
    // End of variables declaration//GEN-END:variables
}
