/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compras.vista;

import compras.modelo.daoProducto;
import compras.modelo.daoCompras;
import compras.controlador.clsProducto;
import compras.controlador.clsCompras;
import compras.controlador.clsProveedor;
import compras.modelo.daoProveedor;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author visitante
 */
public class frmProcesoCompras extends javax.swing.JInternalFrame {

    public void llenadoDeCombos() {
        daoProveedor provDAO = new daoProveedor();
        List<clsProveedor> proveedor = provDAO.select();

        cbx_Proveedor.addItem("Seleccione Un Codigo");
        for (int i = 0; i < proveedor.size(); i++) {
            cbx_Proveedor.addItem(String.valueOf(proveedor.get(i).getprovid()));
        }

        daoProducto productoDao = new daoProducto();
        List<clsProducto> producto = productoDao.select();
        cbx_Producto.addItem("Seleccione Un codigo");
        for (int i = 0; i < producto.size(); i++) {
            cbx_Producto.addItem(String.valueOf(producto.get(i).getProdid()));

        }
    }

    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Compra");
        modelo.addColumn("ID Proveedor");
        modelo.addColumn("Serie");
        modelo.addColumn("Orden");
        modelo.addColumn("ID Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Costo");
        modelo.addColumn("Emision");
        modelo.addColumn("Vencimiento");
        daoCompras productoDAO = new daoCompras();
        List<clsCompras> producto = productoDAO.select();
        List<clsCompras> producto2 = productoDAO.select2();
        tablaVendedores.setModel(modelo);
        String[] dato = new String[9];
        for (int i = 0; i < producto.size(); i++) {
            dato[0] = Integer.toString(producto.get(i).getComid());
            dato[1] = Integer.toString(producto.get(i).getProvid());
            dato[2] = Integer.toString(producto.get(i).getComserie());
            dato[3] = Integer.toString(producto.get(i).getOrdid());
            dato[4] = Integer.toString(producto2.get(i).getProdid());
            dato[5] = Integer.toString(producto2.get(i).getOrdcantidad());
            dato[6] = Integer.toString(producto2.get(i).getOrdcosto());
            dato[7] = producto2.get(i).getComfechaemi();
            dato[8] = producto2.get(i).getComfechavenci();

            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscarProducto() {
        clsCompras productoAConsultar = new clsCompras();
        daoCompras productoDAO = new daoCompras();
        clsCompras productoAConsultar2 = new clsCompras();
        daoCompras productoDAO2 = new daoCompras();
        productoAConsultar.setComid(Integer.parseInt(txtbuscado.getText()));
        productoAConsultar2.setComid(Integer.parseInt(txtbuscado.getText()));
        productoAConsultar = productoDAO.query(productoAConsultar);
        productoAConsultar2 = productoDAO2.query2(productoAConsultar2);
        txtProveedor.setText(String.valueOf(productoAConsultar.getProvid()));
        txtSerie.setText(String.valueOf(productoAConsultar.getComserie()));
        txtOrd.setText(String.valueOf(productoAConsultar.getOrdid()));
        txtProducto.setText(String.valueOf(productoAConsultar2.getProdid()));
        txtCantidad.setText(String.valueOf(productoAConsultar2.getOrdcantidad()));
        txtCosto.setText(String.valueOf(productoAConsultar2.getOrdcosto()));
        lblEmi.setText(productoAConsultar2.getComfechaemi());
        lblVenci.setText(productoAConsultar2.getComfechavenci());

    }

    public frmProcesoCompras() {
        initComponents();
        llenadoDeTablas();
        llenadoDeCombos();
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        txtCantidad = new javax.swing.JTextField();
        label5 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        label8 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        cbx_Producto = new javax.swing.JComboBox<>();
        txtSerie = new javax.swing.JTextField();
        txtVenci = new com.toedter.calendar.JDateChooser();
        txtProducto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtEmi = new com.toedter.calendar.JDateChooser();
        txtOrd = new javax.swing.JTextField();
        cbx_Proveedor = new javax.swing.JComboBox<>();
        txtProveedor = new javax.swing.JLabel();
        lblVenci = new javax.swing.JLabel();
        lblEmi = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtVenci1 = new com.toedter.calendar.JDateChooser();
        txtOrd1 = new javax.swing.JTextField();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento Compras");
        setPreferredSize(new java.awt.Dimension(1500, 700));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 95, 30));

        btnRegistrar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnRegistrar.setText("Regisrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 90, 30));

        btnBuscar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnBuscar.setText("🔍");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 50, 30));

        label1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label1.setText("COMPRAS");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, -1, 20));

        btnModificar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 110, 30));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label3.setText("CODIGO DE COMPRA");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 180, -1));

        txtbuscado.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtbuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 102, -1));

        btnLimpiar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnLimpiar.setText("🗑️");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 40, 30));

        tablaVendedores.setBackground(new java.awt.Color(204, 255, 255));
        tablaVendedores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        tablaVendedores.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        tablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Vendedor", "ID Empleado", "Correo", "Telefono", "Direccion", "Porcentaje", "Comision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVendedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 880, 430));

        txtCantidad.setBackground(new java.awt.Color(255, 255, 255));
        txtCantidad.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(0, 51, 255));
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 220, 20));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label5.setText("Cantidad de Orden");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        lb.setForeground(new java.awt.Color(204, 204, 204));
        lb.setText(".");
        getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 13, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, 30));

        label6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label6.setText("Numero De Serie");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        label7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label7.setText("Numero De orden");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        label4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label4.setText("Codigo Proveedor");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 40, -1));

        label8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label8.setText("ID producto");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        txtCosto.setBackground(new java.awt.Color(255, 255, 255));
        txtCosto.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        txtCosto.setForeground(new java.awt.Color(0, 51, 255));
        txtCosto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCosto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 220, 20));

        label9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label9.setText("Costo De Orden");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        label10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label10.setText("Emision");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        label11.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label11.setText("Vencimiento");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        cbx_Producto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbx_Producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbx_Producto.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cbx_Producto.setDoubleBuffered(true);
        cbx_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_ProductoActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 130, -1));

        txtSerie.setBackground(new java.awt.Color(255, 255, 255));
        txtSerie.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        txtSerie.setForeground(new java.awt.Color(0, 51, 255));
        txtSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSerie.setActionCommand("<Not Set>");
        txtSerie.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 220, 20));
        getContentPane().add(txtVenci, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 220, -1));

        txtProducto.setBackground(new java.awt.Color(153, 153, 153));
        txtProducto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(0, 51, 255));
        txtProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 40, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtEmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 220, -1));

        txtOrd.setBackground(new java.awt.Color(255, 255, 255));
        txtOrd.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        txtOrd.setForeground(new java.awt.Color(0, 51, 255));
        txtOrd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOrd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 20));

        cbx_Proveedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbx_Proveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbx_Proveedor.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cbx_Proveedor.setDoubleBuffered(true);
        cbx_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_ProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(cbx_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 130, -1));

        txtProveedor.setBackground(new java.awt.Color(255, 255, 255));
        txtProveedor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtProveedor.setForeground(new java.awt.Color(0, 51, 255));
        txtProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 40, 30));

        lblVenci.setBackground(new java.awt.Color(51, 51, 255));
        lblVenci.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblVenci.setForeground(new java.awt.Color(0, 51, 255));
        lblVenci.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblVenci, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 170, 20));

        lblEmi.setBackground(new java.awt.Color(51, 51, 255));
        lblEmi.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblEmi.setForeground(new java.awt.Color(0, 51, 255));
        lblEmi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblEmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 500, 360));

        label12.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label12.setText("Vencimiento");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        label13.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label13.setText("Vencimiento");
        getContentPane().add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("INGRESO DE DATOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));
        getContentPane().add(txtVenci1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 220, -1));

        txtOrd1.setBackground(new java.awt.Color(255, 255, 255));
        txtOrd1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        txtOrd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOrd1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtOrd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrd1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtOrd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        daoCompras productoDAO = new daoCompras();
        clsCompras productoAEliminar = new clsCompras();
        productoAEliminar.setComid(Integer.parseInt(txtbuscado.getText()));
        productoDAO.delete(productoAEliminar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        daoCompras productoDAO = new daoCompras();
        clsCompras productoAInsertar = new clsCompras();
        clsCompras productoAInsertar2 = new clsCompras();
        productoAInsertar.setProvid(Integer.parseInt(String.valueOf(cbx_Proveedor.getSelectedItem())));
        productoAInsertar.setComserie(Integer.parseInt(txtSerie.getText()));
        productoAInsertar.setOrdid(Integer.parseInt(txtOrd.getText()));
        productoAInsertar2.setProdid(Integer.parseInt(String.valueOf(cbx_Producto.getSelectedItem())));
        productoAInsertar2.setOrdcantidad(Integer.parseInt(txtCantidad.getText()));
        productoAInsertar2.setOrdcosto(Integer.parseInt(txtCosto.getText()));
        String dia = Integer.toString(txtEmi.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(txtEmi.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(txtEmi.getCalendar().get(Calendar.YEAR));
        String fecha = (year + "-" + mes + "-" + dia);
        productoAInsertar2.setComfechaemi(fecha);
        String dia1 = Integer.toString(txtVenci.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes1 = Integer.toString(txtVenci.getCalendar().get(Calendar.MONTH) + 1);
        String year1 = Integer.toString(txtVenci.getCalendar().get(Calendar.YEAR));
        String fecha2 = (year1 + "-" + mes1 + "-" + dia1);
        productoAInsertar2.setComfechavenci(fecha2);
        productoDAO.insert(productoAInsertar);
        productoDAO.insert2(productoAInsertar2);

        llenadoDeTablas();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        // TODO add your handling code here:
        buscarProducto();


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
//        // TODO add your handling code here:
        daoCompras productoDAO = new daoCompras();
        clsCompras productoAActualizar = new clsCompras();
        daoCompras productoDAO2 = new daoCompras();
        clsCompras productoAActualizar2 = new clsCompras();
        productoAActualizar.setComid(Integer.parseInt(txtbuscado.getText()));
        productoAActualizar.setProvid(Integer.parseInt(String.valueOf(cbx_Proveedor.getSelectedItem())));
        productoAActualizar.setComserie(Integer.parseInt(txtSerie.getText()));
        productoAActualizar.setOrdid(Integer.parseInt(txtOrd.getText()));
        productoAActualizar2.setProdid(Integer.parseInt(String.valueOf(cbx_Producto.getSelectedItem())));
        productoAActualizar2.setOrdcantidad(Integer.parseInt(txtCantidad.getText()));
        productoAActualizar2.setOrdcosto(Integer.parseInt(txtCosto.getText()));
        String dia = Integer.toString(txtEmi.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(txtEmi.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(txtEmi.getCalendar().get(Calendar.YEAR));
        String fecha = (year + "-" + mes + "-" + dia);
        productoAActualizar2.setComfechaemi(fecha);
        String dia1 = Integer.toString(txtVenci.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes1 = Integer.toString(txtVenci.getCalendar().get(Calendar.MONTH) + 1);
        String year1 = Integer.toString(txtVenci.getCalendar().get(Calendar.YEAR));
        String fecha2 = (year1 + "-" + mes1 + "-" + dia1);

        productoAActualizar2.setComfechavenci(fecha2);

        productoDAO.update(productoAActualizar);
        productoDAO2.update2(productoAActualizar2);
        llenadoDeTablas();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        txtProveedor.setText("");
        txtCantidad.setText("");
        txtbuscado.setText("");
        txtProveedor.setText("");
        txtOrd.setText("");
        txtProducto.setText("");
        txtCosto.setText("");
        txtEmi.cleanup();
        txtVenci.cleanup();
        txtSerie.setText("");
        txtOrd.setText("");
        lblEmi.setText("");
        lblVenci.setText("");
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("src\\main\\java\\ayudas\\ProcesoMayor.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ayudas\\ProcesoMayor.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no Fue encontrada");
            }
            System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "INGRESE EL CODIGO DEL PRODUCTO QUE DESEA BUSCAR,ELIMINAR O REGISTRAR");
    }//GEN-LAST:event_jButton1ActionPerformed


    private void cbx_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_ProductoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cbx_ProductoActionPerformed

    private void cbx_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_ProveedorActionPerformed

    private void txtOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdActionPerformed

    private void txtOrd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrd1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbx_Producto;
    private javax.swing.JComboBox<String> cbx_Proveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lblEmi;
    private javax.swing.JLabel lblVenci;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaVendedores;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosto;
    private com.toedter.calendar.JDateChooser txtEmi;
    private javax.swing.JTextField txtOrd;
    private javax.swing.JTextField txtOrd1;
    private javax.swing.JLabel txtProducto;
    private javax.swing.JLabel txtProveedor;
    private javax.swing.JTextField txtSerie;
    private com.toedter.calendar.JDateChooser txtVenci;
    private com.toedter.calendar.JDateChooser txtVenci1;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
