/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compras.vista;

import seguridad.vista.*;
import compras.vista.*;
import compras.controlador.clsProveedor;
import compras.modelo.daoProveedor;
import compras.modelo.daoCompras;
import compras.controlador.clsCompras;
import compras.controlador.clsConcepto;
import compras.modelo.daoConcepto;
import compras.modelo.daoCuentasPorPagar;
import compras.controlador.clsCuentasPorPagar;

import java.util.List;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author visitante
 */
public class frmProcesoCuentasPorPagar extends javax.swing.JInternalFrame {
    
public void llenadoDeCombos() {
        daoConcepto conDAO = new daoConcepto();
        List<clsConcepto> concepto = conDAO.select();

        CbxConcepto.addItem("Seleccione Un Codigo");
        for (int i = 0; i < concepto.size(); i++) {
            CbxConcepto.addItem(String.valueOf(concepto.get(i).getConid()));
        }

        daoCompras comprasDao = new daoCompras();
        List<clsCompras> compra = comprasDao.select();
        CbxCompras.addItem("Seleccione Un codigo");
        for (int i = 0; i < compra.size(); i++) {
            CbxCompras.addItem(String.valueOf(compra.get(i).getComid()));    
        }
         daoProveedor provDao = new daoProveedor();
        List<clsProveedor> proveedor = provDao.select();
        CbxProveedor.addItem("Seleccione Un codigo");
        for (int i = 0; i < proveedor.size(); i++) {
            CbxProveedor.addItem(String.valueOf(proveedor.get(i).getprovid()));
        }
    }
  

    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID CuentaPagar");
        modelo.addColumn("ID Concepto");
        modelo.addColumn("ID Compras");
        modelo.addColumn("ID Proveedor");
        modelo.addColumn("Saldo de cuenta");
        modelo.addColumn("Valor de cuenta");
        modelo.addColumn("Referencia de cuenta");
        modelo.addColumn("Emision");
        modelo.addColumn("Vencimiento");
        
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        List<clsCuentasPorPagar> cuentaporpagar = cuentasDAO.select();
        tablaVendedores.setModel(modelo);
        String[] dato = new String[9];
        for (int i = 0; i < cuentaporpagar.size(); i++) {
            dato[0] = Integer.toString(cuentaporpagar.get(i).getCuentapagarid());
            dato[1] = Integer.toString(cuentaporpagar.get(i).getConid());
            dato[2] = Integer.toString(cuentaporpagar.get(i).getComid());
            dato[3] = Integer.toString(cuentaporpagar.get(i).getProvid());
            dato[4] = Integer.toString(cuentaporpagar.get(i).getCuentasaldo());
            dato[5] = Integer.toString(cuentaporpagar.get(i).getCuentavalor());
            dato[6] = Integer.toString(cuentaporpagar.get(i).getCuentareferencia());
            dato[7] = cuentaporpagar.get(i).getCuentafechaemi();
            dato[8] = cuentaporpagar.get(i).getCuentafechavenci();
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscarCuenta() {
        clsCuentasPorPagar cuentasporpagarAConsultar = new clsCuentasPorPagar();
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        cuentasporpagarAConsultar.setCuentapagarid(Integer.parseInt(txtbuscado.getText()));
        cuentasporpagarAConsultar = cuentasDAO.query(cuentasporpagarAConsultar);
        
        lblConcepto.setText(String.valueOf(cuentasporpagarAConsultar.getConid()));
        lblCompras.setText(String.valueOf(cuentasporpagarAConsultar.getComid()));
        lblProveedor.setText(String.valueOf(cuentasporpagarAConsultar.getProvid()));
        txtCuentSal.setText(String.valueOf(cuentasporpagarAConsultar.getCuentasaldo()));
        txtCuentVal.setText(String.valueOf(cuentasporpagarAConsultar.getCuentavalor()));
        txtCuentRef.setText(String.valueOf(cuentasporpagarAConsultar.getCuentareferencia()));
        lblEmi.setText(cuentasporpagarAConsultar.getCuentafechaemi());
        lblVenci.setText(cuentasporpagarAConsultar.getCuentafechavenci());
        
    }

    public frmProcesoCuentasPorPagar() {
        initComponents();
        llenadoDeTablas();
        llenadoDeCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        lb = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CbxConcepto = new javax.swing.JComboBox<>();
        CbxCompras = new javax.swing.JComboBox<>();
        CbxProveedor = new javax.swing.JComboBox<>();
        label7 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        txtCuentSal = new javax.swing.JTextField();
        label10 = new javax.swing.JLabel();
        txtCuentVal = new javax.swing.JTextField();
        label5 = new javax.swing.JLabel();
        txtCuentRef = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtbuscado = new javax.swing.JTextField();
        label3 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblConcepto = new javax.swing.JLabel();
        lblCompras = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcEmi = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jcVenci = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        lblVenci = new javax.swing.JLabel();
        lblEmi = new javax.swing.JLabel();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Proceso Cuentas por pagar");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setBackground(new java.awt.Color(255, 255, 102));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("?");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 40, 30));

        tablaVendedores.setBackground(new java.awt.Color(204, 255, 255));
        tablaVendedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaVendedores.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Vendedor", "ID Empleado", "Correo", "Telefono", "Direccion", "Porcentaje", "Comision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVendedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1000, 250));

        lb.setForeground(new java.awt.Color(204, 204, 204));
        lb.setText(".");
        getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 13, -1));

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso de Datos"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CbxConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxConceptoActionPerformed(evt);
            }
        });
        jPanel2.add(CbxConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 180, 30));

        CbxCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxComprasActionPerformed(evt);
            }
        });
        jPanel2.add(CbxCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 180, 30));

        CbxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(CbxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 150, 30));

        label7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label7.setText("ID de proveedor");
        jPanel2.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 150, 30));

        label6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label6.setText("ID de compras");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 130, 30));

        label9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label9.setText("Saldo de cuenta");
        jPanel2.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        txtCuentSal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCuentSal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCuentSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentSalActionPerformed(evt);
            }
        });
        jPanel2.add(txtCuentSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 130, 20));

        label10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label10.setText("Valor de la cuenta");
        jPanel2.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 160, 30));

        txtCuentVal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCuentVal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCuentVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentValActionPerformed(evt);
            }
        });
        jPanel2.add(txtCuentVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 140, 20));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label5.setText("Referencia de la cuenta");
        jPanel2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 40));

        txtCuentRef.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCuentRef.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCuentRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentRefActionPerformed(evt);
            }
        });
        jPanel2.add(txtCuentRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 150, 20));
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, -40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("ID de Concepto");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 90, 40));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 90, 40));

        txtbuscado.setBackground(new java.awt.Color(204, 255, 255));
        txtbuscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscadoActionPerformed(evt);
            }
        });
        jPanel2.add(txtbuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 102, 30));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText("Codigo cuenta a buscar:");
        jPanel2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 160, 20));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 90, 40));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 80, 40));

        lblConcepto.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblConcepto.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(lblConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 90, 20));

        lblCompras.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblCompras.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(lblCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 70, 60, 20));

        lblProveedor.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 70, 70, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 270));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(255, 204, 102));
        label1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jPanel3.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setText("Emision");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel3.add(jcEmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setText("Vencimiento");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));
        jPanel3.add(jcVenci, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 150, -1));

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 100, 40));

        lblVenci.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblVenci.setForeground(new java.awt.Color(0, 0, 255));
        jPanel3.add(lblVenci, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 90, 30));

        lblEmi.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblEmi.setForeground(new java.awt.Color(0, 0, 255));
        jPanel3.add(lblEmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 30, 90, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "INGRESE EL CODIGO DEL PROVEEDOR QUE DESEA BUSCAR,ELIMINAR O REGISTRAR");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("src\\main\\java\\ayudas\\ProcesoMayor.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ayudas\\ProcesoMayor.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no Fue encontrada");
            }
            System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
        buscarCuenta();
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        clsCuentasPorPagar cuentasporpagarAEliminar = new clsCuentasPorPagar();
        cuentasporpagarAEliminar.setCuentapagarid(Integer.parseInt(txtbuscado.getText()));
        cuentasDAO.delete(cuentasporpagarAEliminar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        clsCuentasPorPagar cuentasporpagarAInsertar = new clsCuentasPorPagar();
        cuentasporpagarAInsertar.setConid(Integer.parseInt(String.valueOf(CbxConcepto.getSelectedItem())));
        cuentasporpagarAInsertar.setProvid(Integer.parseInt(String.valueOf(CbxProveedor.getSelectedItem())));
        cuentasporpagarAInsertar.setComid(Integer.parseInt(String.valueOf(CbxCompras.getSelectedItem())));
        cuentasporpagarAInsertar.setCuentasaldo(Integer.parseInt(txtCuentSal.getText()));
        cuentasporpagarAInsertar.setCuentavalor(Integer.parseInt(txtCuentVal.getText()));
        cuentasporpagarAInsertar.setCuentareferencia(Integer.parseInt(txtCuentRef.getText()));
        
        String dia = Integer.toString(jcEmi.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(jcEmi.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(jcEmi.getCalendar().get(Calendar.YEAR));
        String fecha = (year + "-" + mes + "-" + dia);
        cuentasporpagarAInsertar.setCuentafechaemi(fecha);
        
        String dia1 = Integer.toString(jcVenci.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes1 = Integer.toString(jcVenci.getCalendar().get(Calendar.MONTH) + 1);
        String year1 = Integer.toString(jcVenci.getCalendar().get(Calendar.YEAR));
        String fecha1 = (year1 + "-" + mes1 + "-" + dia1);
        cuentasporpagarAInsertar.setCuentafechavenci(fecha1);
        
        cuentasDAO.insert(cuentasporpagarAInsertar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtbuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscadoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //        // TODO add your handling code here:
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        clsCuentasPorPagar cuentasporpagarAActualizar = new clsCuentasPorPagar();
        cuentasporpagarAActualizar.setCuentapagarid(Integer.parseInt(txtbuscado.getText()));
        cuentasporpagarAActualizar.setConid(Integer.parseInt(String.valueOf(CbxConcepto.getSelectedItem())));
        cuentasporpagarAActualizar.setProvid(Integer.parseInt(String.valueOf(CbxProveedor.getSelectedItem())));
        cuentasporpagarAActualizar.setComid(Integer.parseInt(String.valueOf(CbxCompras.getSelectedItem())));
        cuentasporpagarAActualizar.setCuentasaldo(Integer.parseInt(txtCuentSal.getText()));
        cuentasporpagarAActualizar.setCuentavalor(Integer.parseInt(txtCuentVal.getText()));
        cuentasporpagarAActualizar.setCuentareferencia(Integer.parseInt(txtCuentRef.getText()));
        
        String dia = Integer.toString(jcEmi.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(jcEmi.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(jcEmi.getCalendar().get(Calendar.YEAR));
        String fecha = (year + "-" + mes + "-" + dia);
        cuentasporpagarAActualizar.setCuentafechaemi(fecha);
        
        String dia1 = Integer.toString(jcVenci.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes1 = Integer.toString(jcVenci.getCalendar().get(Calendar.MONTH) + 1);
        String year1 = Integer.toString(jcVenci.getCalendar().get(Calendar.YEAR));
        String fecha1 = (year1 + "-" + mes1 + "-" + dia1);
        cuentasporpagarAActualizar.setCuentafechavenci(fecha1);
        
        cuentasDAO.update(cuentasporpagarAActualizar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        lblConcepto.setText("");
        lblCompras.setText("");
        lblProveedor.setText("");
        txtCuentSal.setText("");
        txtCuentVal.setText("");
        txtCuentRef.setText("");
        lblEmi.setText("");
        lblVenci.setText("");
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCuentRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentRefActionPerformed

    private void txtCuentValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentValActionPerformed

    private void txtCuentSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentSalActionPerformed

    private void CbxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxProveedorActionPerformed

    private void CbxComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxComprasActionPerformed

    private void CbxConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxConceptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxConceptoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxCompras;
    private javax.swing.JComboBox<String> CbxConcepto;
    private javax.swing.JComboBox<String> CbxProveedor;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jcEmi;
    private com.toedter.calendar.JDateChooser jcVenci;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lblCompras;
    private javax.swing.JLabel lblConcepto;
    private javax.swing.JLabel lblEmi;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblVenci;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaVendedores;
    private javax.swing.JTextField txtCuentRef;
    private javax.swing.JTextField txtCuentSal;
    private javax.swing.JTextField txtCuentVal;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
