/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compras.vista;

import seguridad.vista.*;
import compras.vista.*;
import compras.modelo.daoCuentasPorPagar;
import compras.controlador.clsCuentasPorPagar;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author visitante
 */
public class frmProcesoCuentasPorPagar extends javax.swing.JInternalFrame {

  

    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
         modelo.addColumn("ID CuentaPagar");
        modelo.addColumn("ID Concepto");
        modelo.addColumn("ID Compras");
        modelo.addColumn("ID Proveedor");
        modelo.addColumn("Cuenta de documento");
        modelo.addColumn("Saldo de cuenta");
        modelo.addColumn("Valor de cuenta");
        modelo.addColumn("Referencia de cuenta");
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        List<clsCuentasPorPagar> cuentaporpagar = cuentasDAO.select();
        tablaVendedores.setModel(modelo);
        String[] dato = new String[7];
        for (int i = 0; i < cuentaporpagar.size(); i++) {
            dato[0] = Integer.toString(cuentaporpagar.get(i).getCuentapagarid());
            dato[1] = Integer.toString(cuentaporpagar.get(i).getComid());
            dato[2] = Integer.toString(cuentaporpagar.get(i).getProvid());
            dato[3] = Integer.toString(cuentaporpagar.get(i).getCuentadoc());
            dato[4] = Integer.toString(cuentaporpagar.get(i).getCuentasaldo());
            dato[5] = Integer.toString(cuentaporpagar.get(i).getCuentavalor());
            dato[6] = Integer.toString(cuentaporpagar.get(i).getCuentareferencia());
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscarCuenta() {
        clsCuentasPorPagar cuentasporpagarAConsultar = new clsCuentasPorPagar();
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        cuentasporpagarAConsultar.setCuentapagarid(Integer.parseInt(txtbuscado.getText()));
        cuentasporpagarAConsultar = cuentasDAO.query(cuentasporpagarAConsultar);
        txtConId.setText(String.valueOf(cuentasporpagarAConsultar.getConid()));
        txtComId.setText(String.valueOf(cuentasporpagarAConsultar.getComid()));
        txtProvId.setText(String.valueOf(cuentasporpagarAConsultar.getProvid()));
        txtCuentDoc.setText(String.valueOf(cuentasporpagarAConsultar.getCuentadoc()));
        txtCuentSal.setText(String.valueOf(cuentasporpagarAConsultar.getCuentasaldo()));
        txtCuentVal.setText(String.valueOf(cuentasporpagarAConsultar.getCuentavalor()));
        txtCuentRef.setText(String.valueOf(cuentasporpagarAConsultar.getCuentareferencia()));
       
    }

    public frmProcesoCuentasPorPagar() {
        initComponents();
        llenadoDeTablas();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        label5 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        txtConId = new javax.swing.JTextField();
        txtCuentRef = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtComId = new javax.swing.JTextField();
        txtProvId = new javax.swing.JTextField();
        label8 = new javax.swing.JLabel();
        txtCuentDoc = new javax.swing.JTextField();
        label9 = new javax.swing.JLabel();
        txtCuentSal = new javax.swing.JTextField();
        label10 = new javax.swing.JLabel();
        txtCuentVal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Proceso Cuentas por pagar");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 100, 30));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 95, 30));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 102));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("?");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 40, 30));

        label1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label1.setText("Cuentas por pagar");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 100, 30));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText("Codigo cuenta a buscar:");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 160, 20));

        txtbuscado.setBackground(new java.awt.Color(204, 255, 255));
        txtbuscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtbuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 102, 20));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 95, 30));

        tablaVendedores.setBackground(new java.awt.Color(204, 255, 255));
        tablaVendedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaVendedores.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Vendedor", "ID Empleado", "Correo", "Telefono", "Direccion", "Porcentaje", "Comision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVendedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1000, 250));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label5.setText("Referencia de la cuenta");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 40));

        lb.setForeground(new java.awt.Color(204, 204, 204));
        lb.setText(".");
        getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 13, -1));

        label6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label6.setText("ID de compras");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, 30));

        label7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label7.setText("ID de proveedor");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, 30));

        txtConId.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtConId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtConId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 130, 20));

        txtCuentRef.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCuentRef.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCuentRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentRefActionPerformed(evt);
            }
        });
        getContentPane().add(txtCuentRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 100, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("ID de Concepto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        txtComId.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtComId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtComId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 100, 20));

        txtProvId.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtProvId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtProvId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProvIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtProvId, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 130, 20));

        label8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label8.setText("No. Cuenta");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 30));

        txtCuentDoc.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCuentDoc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCuentDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentDocActionPerformed(evt);
            }
        });
        getContentPane().add(txtCuentDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 130, 20));

        label9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label9.setText("Saldo de cuenta");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtCuentSal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCuentSal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCuentSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentSalActionPerformed(evt);
            }
        });
        getContentPane().add(txtCuentSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, 20));

        label10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label10.setText("Valor de la cuenta");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, 40));

        txtCuentVal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCuentVal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCuentVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentValActionPerformed(evt);
            }
        });
        getContentPane().add(txtCuentVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 130, 20));

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 295, 100, 30));

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1000, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        clsCuentasPorPagar cuentasporpagarAEliminar = new clsCuentasPorPagar();
        cuentasporpagarAEliminar.setCuentapagarid(Integer.parseInt(txtbuscado.getText()));
        cuentasDAO.delete(cuentasporpagarAEliminar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        clsCuentasPorPagar cuentasporpagarAInsertar = new clsCuentasPorPagar();
        cuentasporpagarAInsertar.setConid(Integer.parseInt(txtConId.getText()));
        cuentasporpagarAInsertar.setComid(Integer.parseInt(txtComId.getText()));
        cuentasporpagarAInsertar.setProvid(Integer.parseInt(txtProvId.getText()));
        cuentasporpagarAInsertar.setCuentadoc(Integer.parseInt(txtCuentDoc.getText()));
        cuentasporpagarAInsertar.setCuentasaldo(Integer.parseInt(txtCuentSal.getText()));
        cuentasporpagarAInsertar.setCuentavalor(Integer.parseInt(txtCuentVal.getText()));
        cuentasporpagarAInsertar.setCuentareferencia(Integer.parseInt(txtCuentRef.getText()));
        cuentasDAO.insert(cuentasporpagarAInsertar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "INGRESE EL CODIGO DEL PROVEEDOR QUE DESEA BUSCAR,ELIMINAR O REGISTRAR");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
//        // TODO add your handling code here:
        daoCuentasPorPagar cuentasDAO = new daoCuentasPorPagar();
        clsCuentasPorPagar cuentasporpagarAActualizar = new clsCuentasPorPagar();
        cuentasporpagarAActualizar.setCuentapagarid(Integer.parseInt(txtbuscado.getText()));
        cuentasporpagarAActualizar.setComid(Integer.parseInt(txtComId.getText()));
        cuentasporpagarAActualizar.setProvid(Integer.parseInt(txtProvId.getText()));
        cuentasporpagarAActualizar.setCuentadoc(Integer.parseInt(txtCuentDoc.getText()));
        cuentasporpagarAActualizar.setCuentasaldo(Integer.parseInt(txtCuentSal.getText()));
        cuentasporpagarAActualizar.setCuentavalor(Integer.parseInt(txtCuentVal.getText()));
        cuentasporpagarAActualizar.setCuentareferencia(Integer.parseInt(txtCuentRef.getText())); 
        cuentasDAO.update(cuentasporpagarAActualizar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       
        txtConId.setText("");
        txtComId.setText("");
        txtProvId.setText("");
        txtCuentDoc.setText("");
        txtCuentSal.setText("");
        txtCuentVal.setText("");
        txtCuentRef.setText("");
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("src\\main\\java\\ayudas\\ProcesoMayor.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ayudas\\ProcesoMayor.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no Fue encontrada");
            }
            System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCuentRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentRefActionPerformed

    private void txtProvIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProvIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProvIdActionPerformed

    private void txtCuentDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentDocActionPerformed

    private void txtCuentSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentSalActionPerformed

    private void txtCuentValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentValActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void txtbuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaVendedores;
    private javax.swing.JTextField txtComId;
    private javax.swing.JTextField txtConId;
    private javax.swing.JTextField txtCuentDoc;
    private javax.swing.JTextField txtCuentRef;
    private javax.swing.JTextField txtCuentSal;
    private javax.swing.JTextField txtCuentVal;
    private javax.swing.JTextField txtProvId;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
